---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```


```{r}
df <- read.csv("RoadsProjectScheduleData.csv")

```
```{r}
glimpse (df, width = 75)
```
```{r}
df <- df %>% filter(!df$'Portfolio Category'%in%c ("Quick Response","Contingencies","Administrative","Maintenance Facilities"))
```
```{r}
df <- df %>% filter(!df$Phase%in%c("OPERATIONS","LAND"))

```

```{r}
phasesDF=as.data.frame(table(df$Phase))
names(phasesDF)=c("Phase", "Count")
```
```{r}
phasesDF$Phase <- factor(phasesDF$Phase, levels = c('PLANNING',
                                          'PREDESIGN',
                                          'DESIGN',
                                          'IMPLEMENT',
                                          'CLOSEOUT',
                                          'HOLD',
                                          'NOT SET'))
```
```{r}
library(ggplot2)

base=ggplot(data=phasesDF, aes(x=Phase,y=Count))
base+geom_bar(stat = "identity")
```
```{r}
df2 <- df %>% select(Phase, Master)

tab_All <- df2 %>% select(-Master) %>% table() %>% as_tibble() %>% rename(Phase = ".", Count = n)
tab_M_Yes <- df2 %>% filter(Master == "Yes") %>% table() %>% as_tibble() %>% rename(Count = n)
tab_M_No <- df2 %>% filter(Master == "No") %>% table() %>% as_tibble() %>% rename(Count = n)

title_Text <- 'Total number of projects by phase'
X_axis_title <- 'Project Phases'
max <- as.integer(max(tab_All$Count)) 
```
```{r}
data <- tab_All
data$Phase <- factor(data$Phase, levels = c('PLANNING',
                                          'PREDESIGN',
                                          'DESIGN',
                                          'IMPLEMENT',
                                          'CLOSEOUT',
                                          'HOLD',
                                          'NOT SET'))
```


```{r}
base <- ggplot(data, aes(x = Phase,
                   y = Count,
                   label = Count)) +
  theme_classic()
```
```{r}
lolliplot_All = base + 
  geom_segment(aes(y = 0, 
                   yend = Count, 
                   x = Phase, 
                   xend = Phase),
               color = "gray")  +
  
 geom_point(size = 4, color = "Blue") +
  geom_text(nudge_x=0.3,show.legend = FALSE) +
  geom_hline(yintercept = 0) +
  scale_y_continuous(limits = c(0, max)) + 
  theme(axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.line.x = element_blank()) +
  labs(title = title_Text) +
  xlab(X_axis_title)
```
```{r}
lolliplot_All
```
```{r}
(Table1=table(df$`Portfolio Category`,df$Phase))
```
```{r}
Table1DF=as.data.frame(Table1)
names (Table1DF)=c("Program", "Project_Phase", "Count")
Table1DF
```


```{r}
lubridate::as_date()
```
#what do to at this step...


```{r}
df2 <- df %>% select(Name, 'Portfolio Category', `Gate 2`, `Gate 2 (Performance/Reference)`) %>% drop_na() %>%
  mutate(schedule_difference = (`Gate 2 (Performance/Reference)`- `Gate 2`),
         p_schedule_difference = (schedule_difference / `Gate 2 (Performance/Reference)`))
```



